name: validate-prompts
on: [push, pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: |
          python3 Vault/tools/update_checksums.py
          python3 Vault/tools/build_catalog.py
          python3 Vault/tools/validate_all.py
